Add specs for users and posts
Thinus01/DailyBloggers pull request #5
Opened 2023-04-21 13:26 UTC by Thinus01

2023-04-21 14:54 UTC, franclobo requested changes
Hi @Thinus01, 

# ♻️ Required Changes ♻️

![so-close-jim-halpert](https://user-images.githubusercontent.com/58642949/233667759-55aee475-6802-4e64-a30c-1be0dd95873f.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Correct Git flow ✔️ 
- Descriptive PR ✔️ 
- No linter errors ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] It is not possible to run the tests, please 🙏🏽 fix the issues 👇🏽 

![image](https://user-images.githubusercontent.com/58642949/233667375-4b914d86-0c39-4746-b7fc-11b7602a5125.png)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 19:00 UTC, BenMukebo requested changes
Hi @Thinus01, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight :clap: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 
- Spec file include tests that ensures correct view template is rendered. ✔️  
- Spec file include tests that ensures the response body includes the correct placeholder text. ✔️  


 ## Required Changes ♻️
_Check the comments under the review._

You have submitted a project, that Linters check are not running in the GitHub/action
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._



Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please Tag me on (@BenMukebo) when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-21 19:00 UTC, BenMukebo commented on spec/requests/posts_spec.rb
> +    it 'renders the correct template' do
- [ ] As requested by the previous reviouwer, Kindly fix the tests error 👇🏻 

![image](https://user-images.githubusercontent.com/79058364/233714254-576cf82d-5ad2-4ea7-af17-99c8295af1cb.png)

2023-04-25 11:47 UTC, Thinus01 commented
![rorfixed](https://user-images.githubusercontent.com/78565848/234266528-68849631-d9b0-4f5c-a96a-b3d59dfbaf51.JPG)

Screenshot after fixing linters, showing that the code works on my side.

2023-04-25 12:04 UTC, rotimiazeez approved these changes
Hi @Thinus01 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights.✔️
- `index` and `show` actions for User and Post controllers are tested 😊
- RSpec is correctly added to the gem file 👏🏾 
- All tests passed ✔️
- Good PR description/summary 👍🏼
- Descriptive README file 🙂
- No Linter error ✅️ 

# Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 12:47 UTC, merged